version: "3.8"

services:
  app:
    container_name: app-frontend
    image: app-frontend
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 4000:3000
