name: Apply Terraform
on:
  workflow_dispatch:
defaults:
  run:
    working-directory: ./terraform

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"



jobs:
  terraform:
    name: Plan Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - shell: bash
        run: |
          sudo apt update
          sudo apt install -y make

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
     
      - name: Terraform Initialize
        run: make tf_init
     
      - name: Apply Terraform
        run: make tf_apply