name: build-docker-image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: build-docker-image
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          sudo apt update
          sudo apt install -y make
          docker version

      - run: make all
