name: build-docker-image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: build-docker-image
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          sudo apt update
          sudo apt install -y make
      - shell: bash
        run: |
          cd go-svc
          make docker-build IMAGE_NAME="mehedi02/my-golang-service" TAG="latest"